name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_linux_x64:
    name: Build and run (Linux x64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Test
        run: nix develop -c bash -c 'zig build test -Dtarget=x86_64-linux-musl'
  build_macos_arm64:
    name: Build and run (macOS ARM64)
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Test
        run: nix develop -c bash -c 'zig build test'
