name: Build Python package

on:
  pull_request:
  push:
    branches: [ "main" ]
    tags:
      # Run on version tags
      - '*.*.*'

env:
  ZIG_VERSION: 0.15.1

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Zig
        uses: mlugg/setup-zig@v2.0.5
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: echo "ZIG_PATH=$(dirname $(which zig))" >> $GITHUB_ENV
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: 'cp39-* cp310-* cp311-* cp312-* cp313-*'
          CIBW_ARCHS_LINUX: 'x86_64'
          CIBW_ENVIRONMENT: 'PATH=$PATH:${{ env.ZIG_PATH }}/'
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
        with:
          output-dir: wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ runner.arch }}
          path: ./wheelhouse/*.whl
  pypi_publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs: build_wheels
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/microkit_sdfgen
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download wheel artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: cibw-wheels-*
    - name: Copy into dist directory
      run: |
        mkdir dist
        cp -r cibw-wheels-*/* dist/
        ls -l dist/
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
